// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMSPzFVmhuM3fqcREd48L-Dgv3am_lWTE',
    appId: '1:915070526398:web:5203834c78716a287c0fef',
    messagingSenderId: '915070526398',
    projectId: 'kandygo-1234',
    authDomain: 'kandygo-1234.firebaseapp.com',
    storageBucket: 'kandygo-1234.firebasestorage.app',
    measurementId: 'G-XV5KG8BD1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZcJjiUj2F-mPfUMFwVA2b2sJTGHk6ASE',
    appId: '1:915070526398:android:368b593a87044a7c7c0fef',
    messagingSenderId: '915070526398',
    projectId: 'kandygo-1234',
    storageBucket: 'kandygo-1234.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6p5lkhitTkNcGLFOGSP81QSAzmhCjCfY',
    appId: '1:915070526398:ios:4b87d608ed02e0bc7c0fef',
    messagingSenderId: '915070526398',
    projectId: 'kandygo-1234',
    storageBucket: 'kandygo-1234.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6p5lkhitTkNcGLFOGSP81QSAzmhCjCfY',
    appId: '1:915070526398:ios:4b87d608ed02e0bc7c0fef',
    messagingSenderId: '915070526398',
    projectId: 'kandygo-1234',
    storageBucket: 'kandygo-1234.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMSPzFVmhuM3fqcREd48L-Dgv3am_lWTE',
    appId: '1:915070526398:web:f2222a825ee1ff6a7c0fef',
    messagingSenderId: '915070526398',
    projectId: 'kandygo-1234',
    authDomain: 'kandygo-1234.firebaseapp.com',
    storageBucket: 'kandygo-1234.firebasestorage.app',
    measurementId: 'G-T4YV2XM896',
  );
}
